name: Auto message for Issues

on: [issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: ' Hello there!👋 Welcome to the project!🚀⚡. Thank you and congrats🎉 for opening your very first issue in this project.  Follow [this](https://github.com/Anmol-Baranwal/Hack-Your-Growth/blob/main/CONTRIBUTING.md) to contribute to this repository '
  
